In [43]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [14]:
df_empreendimento = pd.read_json("dadospelt/vw_empreendimento.json")
df_empreendimento = pd.json_normalize(df_empreendimento['vw_empreendimento'])

In [27]:
df_empreendimento[['id_empreendimento', 'origem_ajustada', 'tipos_infraestruturas', 'nome_empreendimento']]

,id_empreendimento,origem_ajustada,tipos_infraestruturas,nome_empreendimento
0,1,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",BR 040 – entre BH e div. MG/GO
1,2,PELT 2007,"{""Trecho rodoviário""}",BR 040 – entre BH e div. MG/RJ
2,3,PELT 2007,"{""Trecho rodoviário""}",BR 262 – entre Entr. p/ Bela Vista de Minas e ...
3,4,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",BR 262 – entre Betim e Uberaba
4,5,PELT 2007,"{""Trecho rodoviário""}",BR 381 – entre BH e Governador Valadares
...,...,...,...,...
1937,1889,CODEMGE,{Oleoduto},Operação de dutovia em OSBRA 20 POL (REPLAN - ...
1938,1890,CODEMGE,{Gasoduto},Operação de dutovia em GASBEL (REDUC/REGAP)
1939,1891,CODEMGE,{Gasoduto},Operação de dutovia em Paulínia-Jacutinga
1940,1932,GERDAU,{Mineroduto},Implantação de Mineroduto em Ouro Preto/MG - O...
1941,1948,GASMIG,"{Gasoduto,""Terminal de Cargas""}",Gasoduto Gasmig Centro Oeste

In [ ]:
df_extensao = pd.read_json("dadospelt/mvw_geo_extensao.json")
df_extensao = pd.json_normalize(df_extensao['mvw_geo_extensao'])

In [ ]:
df_extensao['extensao_km'] = pd.to_numeric(df_extensao['extensao_km'], errors='coerce')
df_extensao['extensao_km'] = df_extensao['extensao_km'].replace([np.inf, -np.inf], np.nan)
df_extensao['extensao_km'] = df_extensao['extensao_km'].round()
df_extensao['extensao_km'] = df_extensao['extensao_km'].astype('Int64')

In [36]:
df_extensao

      id_empreendimento  extensao_km
0                     1   460.959844
1                     2   299.098993
2                     3   192.792069
3                     4   446.391005
4                     5   307.835913
...                 ...          ...
1934               1889   784.378080
1935               1890   352.093811
1936               1891    91.316447
1937               1932    14.657760
1938               1948   186.879689

[1939 rows x 2 columns]

In [29]:
df_gestao_carteiras = pd.read_json("dadospelt/vw_gestao_carteiras.json")
df_gestao_carteiras = pd.json_normalize(df_gestao_carteiras['vw_gestao_carteiras'])
df_gestao_carteiras[['id_empreendimento', 'impacto_avaliado_1_pond_cenario', 'receita']]

      id_empreendimento impacto_avaliado_1_pond_cenario       receita
0                    11                    Alto impacto  1.772959e+09
1                    12                   Médio impacto  1.725776e+09
2                    13                   Médio impacto  4.284536e+09
3                    18                    Alto impacto  3.525546e+09
4                    35                   Médio impacto           NaN
...                 ...                             ...           ...
1673               1964                    Alto impacto           NaN
1674               1970                   Médio impacto           NaN
1675                 29                    Alto impacto  3.114839e+09
1676                417                    Alto impacto           NaN
1677                 31                    Alto impacto  2.498975e+09

[1678 rows x 3 columns]

In [30]:
df = pd.read_parquet("dados_consolidados.parquet")

In [44]:
df

,id_empreendimento,origem_ajustada,tipos_infraestruturas,nome_empreendimento,setor,descr_status_empreendimento,natureza_empreendimento,esfera_acao,grupo_modelagem,responsavel_gestao_infraestrutura,tirm,viabilidade,dimensao_financeira,dimensao_socioeconomica_pond,dimensao_estrategica,ic_1_pond,municipio,Rodovias,link_formulario,capex,opex,carteira_classificada,regiao_geografica_intermediaria,extensao_km,impacto_avaliado_1_pond_cenario,receita
0,11,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário na BR 153: div....,Rodoviário,Concepção,Transporte de Cargas e Pessoas,Federal,Caso geral - infraestruturas lineares,Triunfo Concebra,0.112115,Alta viabilidade,0.829848,0.158500,0.029909,0.209693,"[Itumbiara, Monte Alegre de Minas, Comendador ...",[BR-153],https://forms.pelt.mg.gov.br/avaliar/11,1.268445e+09,1.123160e+09,1.0,"[Uberaba, Uberlândia, Itumbiara]",235.624964,Alto impacto,1.772959e+09
1,12,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário na BR 251: Mont...,Rodoviário,Concepção,Transporte de Cargas e Pessoas,Federal,Caso geral - infraestruturas lineares,DNIT,0.026073,Média viabilidade,0.527264,0.210893,0.028751,0.160255,"[Salinas, Fruta de Leite, Francisco Sá, Santa ...","[BR-251, BR-116]",https://forms.pelt.mg.gov.br/avaliar/12,1.586033e+09,1.540566e+09,1.0,"[Montes Claros, Teófilo Otoni]",321.565877,Médio impacto,1.725776e+09
2,13,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário na BR 365: Uber...,Rodoviário,Concepção,Transporte de Cargas e Pessoas,Federal,Caso geral - infraestruturas lineares,EPR Triângulo,0.007344,Média viabilidade,0.461397,0.204966,0.065963,0.154470,"[Patrocínio, São Gonçalo do Abaeté, Indianópol...",[BR-365],https://forms.pelt.mg.gov.br/avaliar/13,4.311709e+09,2.925072e+09,1.0,"[Montes Claros, Uberlândia, Patos de Minas]",610.558986,Médio impacto,4.284536e+09
3,18,PELT 2007,"{""Trecho rodoviário""}",AMG-1520/AMG-1550/BR-146/MG-459/BR-267/MG-290/...,Rodoviário,Concepção,Transporte de Cargas e Pessoas,Estadual,Caso geral - infraestruturas lineares,DER-MG,-0.007514,Baixa viabilidade,1.000000,0.115430,0.038716,0.210941,"[Andradas, Pouso Alegre, Borda da Mata, Monte ...","[MG-455, AMG-1520, MG-290, MG-295, MGT-482, BR...",https://forms.pelt.mg.gov.br/avaliar/18,3.964090e+09,1.320657e+09,1.0,[Pouso Alegre],275.924304,Alto impacto,3.525546e+09
4,29,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",AMG-2535/AMG-2540/BR-364/BR-497/LMG-732/LMG-81...,Rodoviário,Concepção,Transporte de Cargas e Pessoas,Estadual,Caso geral - infraestruturas lineares,DER-MG,0.075304,Média viabilidade,1.000000,0.208451,0.044454,0.247993,"[Planura, Pirajuba, Conceição das Alagoas, Itu...","[AMG-2535, MG-427, MGT-497, AMG-2540, MG-426, ...",https://forms.pelt.mg.gov.br/avaliar/29,NaN,NaN,1.0,"[Uberaba, Uberlândia, São José do Rio Preto]",507.988161,Alto impacto,3.114839e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673,1889,CODEMGE,{Oleoduto},Operação de dutovia em OSBRA 20 POL (REPLAN - ...,Dutoviário,Contratado - em execução,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,UN-BSOL,NaN,Não se aplica,0.000000,0.161004,0.027476,0.042615,"[São Joaquim da Barra, Hidrolândia, São Simão,...",[],https://forms.pelt.mg.gov.br/avaliar/1889,NaN,NaN,0.0,"[Uberaba, Uberlândia, Ribeirão Preto, Araraqua...",784.378080,Baixo impacto,NaN
1674,1890,CODEMGE,{Gasoduto},Operação de dutovia em GASBEL (REDUC/REGAP),Dutoviário,Contratado - em execução,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,UN-SEAL,NaN,Não se aplica,0.000000,0.194942,0.013377,0.046891,"[Queluzito, Cristiano Otoni, Sarzedo, Jeceaba,...",[],https://forms.pelt.mg.gov.br/avaliar/1890,NaN,NaN,0.0,"[Belo Horizonte, Juíz de Fora, Barbacena, Rio ...",352.093811,Baixo impacto,NaN
1675,1891,CODEMGE,{Gasoduto},Operação de dutovia em Paulínia-Jacutinga,Dutoviário,Contratado - em execução,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,DT/REGIONAL SE,NaN,Não se aplica,0.000000,0.141889,0.000637,0.031976,"[Santo Antônio de Posse, Mogi-Mirim, Holambra,...",[],https://forms.pelt.mg.gov.br/avaliar/1891,NaN,NaN,0.0,"[Pouso Alegre, Campinas]",91.316447,Baixo impacto,NaN
1676,1932,GERDAU,{Mineroduto},Implantação de Mineroduto em Ouro Preto/MG - O...,Dutoviário,Concepção,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,GERDAU,NaN,Não se aplica,0.000000,0.147287,0.000000,0.033036,"[Ouro Preto, Congonhas]",[],https://forms.pelt.mg.gov.br/avaliar/1932,9.553180e+08,8.597862e+08,0.0,"[Belo Horizonte, Barbacena]",14.657760,Baixo impacto,NaN
1677,1948,GASMIG,"{Gasoduto,""Terminal de Cargas""}",Gasoduto Gasmig Centro Oeste,Dutoviário,Contratado - em execução,Transporte de Cargas,Estadual,Caso geral - infraestruturas lineares,GASMIG,NaN,Não se aplica,0.000000,0.376222,0.000000,0.084386,"[Juatuba, Igarapé, Itaúna, Carmo do Cajuru, Di...",[],https://forms.pelt.mg.gov.br/avaliar/1948,7.800000e+08,7.020000e+08,1.0,"[Belo Horizonte, Divinópolis]",186.879689,Médio impacto,NaN