In [1]:
import pandas as pd
import numpy as np
import re
pd.set_option('display.max_columns', None)

In [2]:
df_empreendimento = pd.read_json("dadospelt/vw_empreendimento.json")
df_empreendimento = pd.json_normalize(df_empreendimento['vw_empreendimento'])

In [3]:
df_empreendimento[['id_empreendimento', 'origem_ajustada', 'tipos_infraestruturas','intervencao_principal', 'nome_empreendimento']]

,id_empreendimento,origem_ajustada,tipos_infraestruturas,intervencao_principal,nome_empreendimento
0,1,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário,BR 040 – entre BH e div. MG/GO
1,2,PELT 2007,"{""Trecho rodoviário""}",Manutenção de trecho rodoviário,BR 040 – entre BH e div. MG/RJ
2,3,PELT 2007,"{""Trecho rodoviário""}",Manutenção de trecho rodoviário,BR 262 – entre Entr. p/ Bela Vista de Minas e ...
3,4,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário,BR 262 – entre Betim e Uberaba
4,5,PELT 2007,"{""Trecho rodoviário""}",Ampliação de trecho rodoviário,BR 381 – entre BH e Governador Valadares
...,...,...,...,...,...
1937,1889,CODEMGE,{Oleoduto},Operação de dutovia,Operação de dutovia em OSBRA 20 POL (REPLAN - ...
1938,1890,CODEMGE,{Gasoduto},Operação de dutovia,Operação de dutovia em GASBEL (REDUC/REGAP)
1939,1891,CODEMGE,{Gasoduto},Operação de dutovia,Operação de dutovia em Paulínia-Jacutinga
1940,1932,GERDAU,{Mineroduto},Operação de dutovia,Implantação de Mineroduto em Ouro Preto/MG - O...
1941,1948,GASMIG,"{Gasoduto,""Terminal de Cargas""}",Implantação de dutovia,Gasoduto Gasmig Centro Oeste

In [4]:
df_empreendimento[df_empreendimento['id_empreendimento'] == 1994]

,id_empreendimento,nome_empreendimento,id_setor,setor,origem,id_nat_empreendimento,natureza_empreendimento,numero_obras,status_obras,status_empreendimento,descr_status_empreendimento,fonte_financiamento,ids_intervencoes,intervencoes,ids_tipo_infraestruturas,tipos_infraestruturas,origem_ajustada,id_esfera_acao,esfera_acao,responsavel_gestao_infraestrutura,intervencao_principal,grupo_intervencao_principal,id_grupo_modelagem,grupo_modelagem,empreendimento_linear
1872,1994,Reestruturação da Ferrovia Bahia - Minas,2,Ferroviário,MTC Caravelas,2,Transporte de Cargas,34,"{6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6...",6,Contratado - execução não iniciada,Privado,"{12,14,57}","{Aquisição,Implantação,""Operação de transporte...","{8,10,13,67}","{""Material rodante para Transporte de Cargas"",...",MTC Caravelas,1.0,Federal,MTC Caravelas,Implantação de trecho ferroviário,Implantação,1.0,Caso geral - infraestruturas lineares,False

In [ ]:
df_extensao = pd.read_json("dadospelt/mvw_geo_extensao.json")
df_extensao = pd.json_normalize(df_extensao['mvw_geo_extensao'])

In [ ]:
df_extensao['extensao_km'] = pd.to_numeric(df_extensao['extensao_km'], errors='coerce')
df_extensao['extensao_km'] = df_extensao['extensao_km'].replace([np.inf, -np.inf], np.nan)
df_extensao['extensao_km'] = df_extensao['extensao_km'].round()
df_extensao['extensao_km'] = df_extensao['extensao_km'].astype('Int64')

In [36]:
df_extensao

      id_empreendimento  extensao_km
0                     1   460.959844
1                     2   299.098993
2                     3   192.792069
3                     4   446.391005
4                     5   307.835913
...                 ...          ...
1934               1889   784.378080
1935               1890   352.093811
1936               1891    91.316447
1937               1932    14.657760
1938               1948   186.879689

[1939 rows x 2 columns]

In [29]:
df_gestao_carteiras = pd.read_json("dadospelt/vw_gestao_carteiras.json")
df_gestao_carteiras = pd.json_normalize(df_gestao_carteiras['vw_gestao_carteiras'])
df_gestao_carteiras[['id_empreendimento', 'impacto_avaliado_1_pond_cenario', 'receita']]

      id_empreendimento impacto_avaliado_1_pond_cenario       receita
0                    11                    Alto impacto  1.772959e+09
1                    12                   Médio impacto  1.725776e+09
2                    13                   Médio impacto  4.284536e+09
3                    18                    Alto impacto  3.525546e+09
4                    35                   Médio impacto           NaN
...                 ...                             ...           ...
1673               1964                    Alto impacto           NaN
1674               1970                   Médio impacto           NaN
1675                 29                    Alto impacto  3.114839e+09
1676                417                    Alto impacto           NaN
1677                 31                    Alto impacto  2.498975e+09

[1678 rows x 3 columns]

In [7]:
df = pd.read_parquet("dados_consolidados.parquet")

In [ ]:
df1994 = pd.read_json('dadospelt/mvw_atlas_comercial_emp1994.json')
df1994 = pd.json_normalize(df1994['mvw_atlas_comercial_emp1994'])
df_emp1994 = df1994[['id_empreendimento', 'origem_ajustada', 'nome_empreendimento', 'setor', 'descr_status_empreendimento', 'natureza_empreendimento', 'esfera_acao', 'grupo_modelagem', 'responsavel_gestao_infraestrutura', 'tirm', 'viabilidade', 'ic_1_pond', 'CAPEX', 'OPEX', 'receita']]
df_emp1994.rename(columns={'CAPEX': 'capex', 'OPEX': 'opex'},inplace=True)

In [44]:
df_consolidado = df

In [45]:
df_resultado = pd.concat([df_consolidado, df_emp1994], ignore_index=True)

C:\Users\pauloferreira\AppData\Local\Temp\ipykernel_10304\3317595860.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_resultado = pd.concat([df_consolidado, df_emp1994], ignore_index=True)

In [46]:
df_resultado[df_resultado['id_empreendimento'] == 1994]

,id_empreendimento,origem_ajustada,tipos_infraestruturas,intervencao_principal,nome_empreendimento,setor,descr_status_empreendimento,natureza_empreendimento,esfera_acao,grupo_modelagem,responsavel_gestao_infraestrutura,tirm,viabilidade,dimensao_financeira,dimensao_socioeconomica_pond,dimensao_estrategica,ic_1_pond,municipio,Rodovias,link_formulario,capex,opex,carteira_classificada,regiao_geografica_intermediaria,extensao_km,impacto_avaliado_1_pond_cenario,receita
319,1994,MTC Caravelas,NaN,NaN,Reestruturação da Ferrovia Bahia - Minas,Ferroviário,Contratado - execução não iniciada,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,MTC Caravelas,NaN,Não se aplica,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.120642e+10,2.483100e+10,NaN,NaN,<NA>,NaN,NaN