In [15]:
import pandas as pd
import numpy as np
import re
pd.set_option('display.max_columns', None)

In [23]:
df_empreendimento = pd.read_json("dadospelt/vw_empreendimento.json")
df_empreendimento = pd.json_normalize(df_empreendimento['vw_empreendimento'])

In [26]:
df_empreendimento[['id_empreendimento', 'origem_ajustada', 'tipos_infraestruturas','intervencao_principal', 'nome_empreendimento']]

,id_empreendimento,origem_ajustada,tipos_infraestruturas,intervencao_principal,nome_empreendimento
0,1,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário,BR 040 – entre BH e div. MG/GO
1,2,PELT 2007,"{""Trecho rodoviário""}",Manutenção de trecho rodoviário,BR 040 – entre BH e div. MG/RJ
2,3,PELT 2007,"{""Trecho rodoviário""}",Manutenção de trecho rodoviário,BR 262 – entre Entr. p/ Bela Vista de Minas e ...
3,4,PELT 2007,"{""Faixa adicional"",""Trecho rodoviário""}",Ampliação de trecho rodoviário,BR 262 – entre Betim e Uberaba
4,5,PELT 2007,"{""Trecho rodoviário""}",Ampliação de trecho rodoviário,BR 381 – entre BH e Governador Valadares
...,...,...,...,...,...
1937,1889,CODEMGE,{Oleoduto},Operação de dutovia,Operação de dutovia em OSBRA 20 POL (REPLAN - ...
1938,1890,CODEMGE,{Gasoduto},Operação de dutovia,Operação de dutovia em GASBEL (REDUC/REGAP)
1939,1891,CODEMGE,{Gasoduto},Operação de dutovia,Operação de dutovia em Paulínia-Jacutinga
1940,1932,GERDAU,{Mineroduto},Operação de dutovia,Implantação de Mineroduto em Ouro Preto/MG - O...
1941,1948,GASMIG,"{Gasoduto,""Terminal de Cargas""}",Implantação de dutovia,Gasoduto Gasmig Centro Oeste

In [ ]:
df_extensao = pd.read_json("dadospelt/mvw_geo_extensao.json")
df_extensao = pd.json_normalize(df_extensao['mvw_geo_extensao'])

In [ ]:
df_extensao['extensao_km'] = pd.to_numeric(df_extensao['extensao_km'], errors='coerce')
df_extensao['extensao_km'] = df_extensao['extensao_km'].replace([np.inf, -np.inf], np.nan)
df_extensao['extensao_km'] = df_extensao['extensao_km'].round()
df_extensao['extensao_km'] = df_extensao['extensao_km'].astype('Int64')

In [36]:
df_extensao

      id_empreendimento  extensao_km
0                     1   460.959844
1                     2   299.098993
2                     3   192.792069
3                     4   446.391005
4                     5   307.835913
...                 ...          ...
1934               1889   784.378080
1935               1890   352.093811
1936               1891    91.316447
1937               1932    14.657760
1938               1948   186.879689

[1939 rows x 2 columns]

In [29]:
df_gestao_carteiras = pd.read_json("dadospelt/vw_gestao_carteiras.json")
df_gestao_carteiras = pd.json_normalize(df_gestao_carteiras['vw_gestao_carteiras'])
df_gestao_carteiras[['id_empreendimento', 'impacto_avaliado_1_pond_cenario', 'receita']]

      id_empreendimento impacto_avaliado_1_pond_cenario       receita
0                    11                    Alto impacto  1.772959e+09
1                    12                   Médio impacto  1.725776e+09
2                    13                   Médio impacto  4.284536e+09
3                    18                    Alto impacto  3.525546e+09
4                    35                   Médio impacto           NaN
...                 ...                             ...           ...
1673               1964                    Alto impacto           NaN
1674               1970                   Médio impacto           NaN
1675                 29                    Alto impacto  3.114839e+09
1676                417                    Alto impacto           NaN
1677                 31                    Alto impacto  2.498975e+09

[1678 rows x 3 columns]

In [ ]:
df = pd.read_parquet("dados_consolidados.parquet")

In [28]:
df[df['extensao_km'] > 999]

,id_empreendimento,origem_ajustada,tipos_infraestruturas,intervencao_principal,nome_empreendimento,setor,descr_status_empreendimento,natureza_empreendimento,esfera_acao,grupo_modelagem,responsavel_gestao_infraestrutura,tirm,viabilidade,dimensao_financeira,dimensao_socioeconomica_pond,dimensao_estrategica,ic_1_pond,municipio,Rodovias,link_formulario,capex,opex,carteira_classificada,regiao_geografica_intermediaria,extensao_km,impacto_avaliado_1_pond_cenario,receita
11,56,ANTT,[Trecho rodoviário],Manutenção de trecho rodoviário,Manutenção de trecho rodoviário na BR-060/153/...,Rodoviário,Contratado - em execução,Transporte de Cargas e Pessoas,Federal,Caso geral - infraestruturas lineares,Concebra,-0.014421,Baixa viabilidade,1.000000,0.219574,0.124383,0.249585,"[Anápolis, São Gonçalo do Pará, Goiatuba, Bom ...",[BR-060],https://forms.pelt.mg.gov.br/avaliar/56,1.348048e+10,8.853483e+09,1.0,"[Belo Horizonte, Uberaba, Uberlândia, Divinópo...",1179,Alto impacto,1.193667e+10
27,112,PNL 2035,[Trecho rodoviário],Ampliação de trecho rodoviário,Ampliação de trecho rodoviário na BR-251/MG,Rodoviário,Estudo,Transporte de Cargas e Pessoas,Federal,Empreendimentos rodoviários de execução públic...,DNIT,NaN,Não se aplica,0.000000,0.231172,0.068208,0.067992,"[Santa Cruz de Salinas, Dom Bosco, Unaí, Monte...",[BR-251],https://forms.pelt.mg.gov.br/avaliar/112,4.665797e+09,4.882833e+09,1.0,"[Vitória da Conquista, Montes Claros, Teófilo ...",1019,Alto impacto,4.712352e+09
1510,57,ANTT,"[Material rodante para Transporte de Cargas, P...",Ampliação de trecho ferroviário,Ampliação de trecho ferroviário em Renovação d...,Ferroviário,Contratado - em execução,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,MRS Logística S.A.,0.597367,Alta viabilidade,1.000000,0.481059,0.267317,0.372476,"[Alfredo Vasconcelos, Rio Acima, Paraíba do Su...",[],https://forms.pelt.mg.gov.br/avaliar/57,9.687000e+09,6.766000e+10,1.0,"[Belo Horizonte, Juíz de Fora, Barbacena, Rio ...",1901,Alto impacto,2.065460e+12
1514,82,ANTT,"[Material rodante para Transporte de Cargas, P...",Implantação de trecho ferroviário,Implantação de trecho ferroviário de Implantaç...,Ferroviário,Estudo,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,Greenfield,-0.234338,Baixa viabilidade,0.000000,0.264357,0.047485,0.070531,"[Itacambira, Unaí, Montes Claros, Teófilo Oton...",[],https://forms.pelt.mg.gov.br/avaliar/82,1.422000e+10,7.815000e+09,0.0,"[Montes Claros, Teófilo Otoni, Patos de Minas,...",1067,Baixo impacto,5.555220e+05
1524,107,ANTT,"[Material rodante para Transporte de Cargas, P...",Implantação de trecho ferroviário,Implantação de trecho ferroviário em Ferrovia ...,Ferroviário,Contratado - em execução,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,Rumo Malha Central S.A.,0.445181,Alta viabilidade,0.817451,0.508567,0.039843,0.214536,"[São Simão, Paraíso do Tocantins, Anápolis, Pa...",[],https://forms.pelt.mg.gov.br/avaliar/107,3.639884e+09,0.000000e+00,1.0,"[Palmas, Araguaína, Gurupi, Imperatriz, Uberab...",1542,Médio impacto,3.096470e+12
1525,108,ANTT,"[Material rodante para Transporte de Cargas, P...",Ampliação de trecho ferroviário,Ampliação de trecho ferroviário em Malha Centr...,Ferroviário,Contratado - em execução,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,VLI Logística,0.594949,Alta viabilidade,1.000000,0.399139,0.443063,0.353056,"[Rio do Antônio, Brumado, Muritiba, Divinópoli...",[],https://forms.pelt.mg.gov.br/avaliar/108,0.000000e+00,7.243930e+08,1.0,"[Petrolina, Aracaju, Itabaiana, Salvador, Sant...",7182,Alto impacto,7.964490e+11
1527,113,ANTT,"[Material rodante para Transporte de Cargas, P...",Ampliação de trecho ferroviário,Renovação da Concessão da Malha Centro-Leste (...,Ferroviário,Em contratação (Licitação/Autorização/Adesão),Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,VLI Logística,0.594949,Alta viabilidade,1.000000,0.508438,0.500000,0.391045,"[Rio do Antônio, Brumado, Muritiba, Divinópoli...",[],https://forms.pelt.mg.gov.br/avaliar/113,2.898924e+08,4.236144e+10,1.0,"[Petrolina, Aracaju, Itabaiana, Salvador, Sant...",7830,Alto impacto,9.097310e+11
1537,147,MT_SNTF,"[Material rodante para Transporte de Cargas, P...",Ampliação de trecho ferroviário,Ampliação de trecho ferroviário em Linha Corin...,Ferroviário,Estudo,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,VLI Logística,-0.078120,Baixa viabilidade,0.187928,0.410097,0.060257,0.144076,"[Engenheiro Navarro, Buenópolis, Salvador, Mon...",[],https://forms.pelt.mg.gov.br/avaliar/147,6.218544e+09,7.815000e+09,0.0,"[Salvador, Santo Antônio de Jesus, Vitória da ...",1357,Baixo impacto,2.093360e+11
1547,726,PEF 2021,"[Material rodante para Transporte de Cargas, P...",Implantação de trecho ferroviário,Implantação de trecho ferroviário em FC 39 Cor...,Ferroviário,Concepção,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,Vale SA,-0.078120,Baixa viabilidade,0.187928,0.452921,0.059150,0.153420,"[Engenheiro Navarro, Buenópolis, Salvador, Mon...",[],https://forms.pelt.mg.gov.br/avaliar/726,1.622466e+10,8.805000e+09,1.0,"[Salvador, Santo Antônio de Jesus, Vitória da ...",1318,Médio impacto,2.206990e+11
1563,742,PEF 2021,"[Material rodante para Transporte de Cargas, P...",Implantação de trecho ferroviário,Implantação de trecho ferroviário em FC 101 An...,Ferroviário,Concepção,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,Greenfield,0.276893,Alta viabilidade,0.615003,0.414094,0.093183,0.238743,"[Dom Bosco, Unaí, Conceição do Mato Dentro, An...",[],https://forms.pelt.mg.gov.br/avaliar/742,1.501176e+10,1.058700e+10,1.0,"[Belo Horizonte, Montes Claros, Teófilo Otoni,...",1540,Médio impacto,1.411720e+12
1613,122,INFRASA,[Trecho hidroviário],Implantação de trecho hidroviário,Manutenção de trecho hidroviário na Hidrovia d...,Hidroviário,Contratado - em execução,Transporte de Cargas e Pessoas,Federal,Caso geral - infraestruturas lineares,DNIT,NaN,Não se aplica,0.000000,0.262344,0.366819,0.145644,"[São Simão, Castilho, Paulicéia, Marechal Când...",[],https://forms.pelt.mg.gov.br/avaliar/122,5.538512e+07,6.490990e+09,1.0,"[Uberaba, Uberlândia, Presidente Prudente, Ara...",1364,Médio impacto,NaN
1663,993,PIO 2022,[Terminal de Cargas],Implantação de dutovia,Implantação de dutovia em Oleoduto Uberaba/MG ...,Dutoviário,Concepção,Transporte de Cargas,Federal,Caso geral - infraestruturas lineares,Greenfield,NaN,Não se aplica,0.000000,0.451893,0.054952,0.114362,"[Pedro Gomes, Planura, Santo Antônio do Leverg...",[],https://forms.pelt.mg.gov.br/avaliar/993,9.916722e+09,8.243100e+09,1.0,"[Uberaba, Uberlândia, Campo Grande, Cuiabá, Ro...",1380,Alto impacto,NaN